# Generated by Django 3.2.19 on 2023-06-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['-food_choice']},
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='food_type',
            new_name='food_choice',
        ),
    ]
