# Generated by Django 3.2.19 on 2023-05-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkitem',
            name='drink_type',
            field=models.IntegerField(choices=[(0, 'White Wine'), (1, 'Red Wine'), (2, 'Beers'), (3, 'Cocktails'), (4, 'New')], default=3),
        ),
    ]
