# Generated by Django 3.2.19 on 2023-06-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
    ]
