# Generated by Django 3.2.19 on 2023-06-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkitem',
            name='drink_type',
            field=models.IntegerField(choices=[(0, 'White Wine'), (1, 'Red Wine'), (2, 'Rose Wine'), (3, 'Prosecco'), (4, 'Beers'), (5, 'Cocktails'), (6, 'Spirits'), (7, 'New')], default=7),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food_type',
            field=models.IntegerField(choices=[(0, 'Starters'), (1, 'Mains'), (2, 'Steaks'), (3, 'Desserts'), (4, 'New')], default=4),
        ),
    ]
