# Generated by Django 3.2.19 on 2023-06-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230620_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkitem',
            name='description',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
