# Generated by Django 3.2.19 on 2023-06-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230620_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['-food_type']},
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='food_choice',
            new_name='food_type',
        ),
    ]
