# Generated by Django 3.2.19 on 2023-05-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_drinkitem_drink_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkitem',
            name='drink_type',
            field=models.IntegerField(choices=[(0, 'White Wine'), (1, 'Red Wine'), (2, 'Rose Wine'), (3, 'Beers'), (4, 'Cocktails'), (5, 'New')], default=3),
        ),
    ]
