# Generated by Django 3.2.19 on 2023-06-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20230620_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkitem',
            name='description',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
