# Generated by Django 3.2.19 on 2023-06-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_drinkitem_drink_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_type',
            field=models.IntegerField(choices=[(0, 'Starters'), (1, 'Mains'), (2, 'Steaks'), (3, 'Desserts'), (4, 'New')], default=3),
        ),
    ]
