# Generated by Django 3.2.19 on 2023-05-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
