# Generated by Django 3.2.19 on 2023-06-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_time_requested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-requested_time']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date_created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='date_requested',
            new_name='requested_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='requested_time',
            field=models.CharField(choices=[('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00')], default='17:00', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('requested_date', 'requested_time')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_requested',
        ),
    ]
